### ISSUE TITLE
Download function results in empty file (GuzzleHttp related)

### ISSUE THREAD

**Issue by vanrooij-it** [thyyppa/laravel-fluent-fm#1]
Hi,

Thanks for your work! I have used it in multiple projects now.

I'm having an issue with file downloads. They result in an empty file. I'm not sure what's happening, but in FluentFMRepository after Response::check($response, $this->query); the content is empy.

A quick fix is to disable Response::check or put $response->getBody()->rewind(); after Response::check. It probably has something to do with GuzzleHttp, but I'm not sure what the exact issue is.

regards,

Marco

**Comment by thyyppa** [comment]
Ah, nice catch! You are right, it was due to the body rewind during response validation. This should be fixed now as of version 1.0.15

Thanks for pointing this out! :)
