### ISSUE TITLE
Multiple field sorts

### ISSUE THREAD

**Issue by frankeg** [thyyppa/laravel-fluent-fm#6]
Can't stack sorts like below
`$result = FluentFM::records('event')->limit(100)->sortDesc('start')->sortAsc('event')->get(); `

Is there a way to sort on multiple fields or is this currently not available ?

Thanks

**Comment by thyyppa** [comment]
I don't think that's currently supported, but it's something that should be. I'll work on this a bit today and report back.

**Comment by frankeg** [comment]
single sort (sortDesc, sortAsc, sort) works the records eg.
`$result = FluentFM::records('event')->limit(100)->sort('id_event', 'asc'),->get();`

but does not work with find eg.
`$result = FluentFM::find('event')->where('id_contact',1000)->sort('id_event', 'asc'),->get();`

hope this helps

**Comment by thyyppa** [comment]
Give v1.1.4 a shot, I reworked a few things. :)

**Comment by frankeg** [comment]
after the update all sorts worked with the find including multiple field sorts :)
thank you

**Comment by thyyppa** [comment]
You're quite welcome, thanks for pointing this out!
